name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: glimps-re/go-actions@v0.3.0
        with:
          go-version: '1.24'
          golangci-lint-version: 'v2.12.2'
