name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: glimps-re/go-actions@v0.1.0
        with:
          golangci-lint-version: v2.2.2
          go-private-repo: github.com/glimps-re/*
          go-private-token: ${{ secrets.GO_PRIVATE_TOKEN }}
